name: dictionary_definitions_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flash: ^3.0.5+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  golden_toolkit: ^0.15.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  mocktail: ^1.0.1
  path_provider: ^2.1.1
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
